language: objective-c
osx_image: xcode7.1
before_install:
  - export LANG=en_US.UTF-8
  - bundle install
  - bundle exec pod install
script:
  - xctool -sdk iphonesimulator -workspace RestKitTest.xcworkspace -scheme RestKitTest clean build &>/dev/null || true
  - xctool -sdk iphonesimulator -workspace RestKitTest.xcworkspace -scheme RestKitTest build
